# Generated by Django 3.1.5 on 2022-02-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestampe',
            new_name='timestamp',
        ),
    ]
